#ifndef APP_DEVICE_H__
#define APP_DEVICE_H__

#include "utilities.h"

#define G_TYPE_SWITCH_BUTTON 0x002a
#define G_TYPE_LM_DIMMER 0x002b
#define G_TYPE_LM_CURTAIN 0x002c
#define G_TYPE_LM_FAN 0x002d
#define G_TYPE_LM_GATE 0x002e

#define DEV_TYPE_SEL G_TYPE_LM_CURTAIN
#define NUMBER_INPUT 1
#define RELAY_CNT NUMBER_INPUT

/*
 * NUMBER INPUT
 */
#define ELE_CNT (NUMBER_INPUT)
#define NUMBER_CURTAIN 1
#define NUMBER_LED 1

#define BACKUP_MASK_RL 0x0F

#define NUMBER_BUTTON 1
#define CONFIG_BUTTON_IDX 0

#define BACKUP_MASK 0xFFFF

#define CONFIG_LED_IDX_BLUETOOTH 0x00
#define CONFIG_LED_IDX_KNX 0x00

#define CONFIG_LED_MASK_BLUETOOTH 0x01
#define CONFIG_LED_MASK_KNX 0x01

#define CONFIG_BTN_ID_BLUETOOTH 0x00
#define CONFIG_BTN_ID_KNX 0x00

#define CONFIG_LED_MASK (CONFIG_LED_MASK_BLUETOOTH)

#define DEVICE_TYPE DEV_SWITCH

#define ADR_FIXED_GROUP_START (0xFF00)

#define LM_SUB_GROUP_ENABLE 1
#define LM_SCENE_ENABLE 1

/* Define GATEWAY_UNICAST_ADDR if not defined */
#ifndef GATEWAY_UNICAST_ADDR
#define GATEWAY_UNICAST_ADDR 0x0001
#endif

#define INTER_PROVISION_EN 0
#define TIMESTAMP_CACULATOR_EN 1
#define MASTER_LED_CONTROL_EN 0
#define TOGGLE_MODE_EN 1
// default transition
#define CTL_WITH_FLAG_DEFAULT_POSITION_EN 1

#if DEV_TYPE_SEL == G_TYPE_SWITCH_BUTTON
#define EN_SWITCH_CONFIG_DIMMING 0
#endif

#define PUBLISH_DELAY_OFFSET 50

/* Enable/Disable provisioning toggle feature (double press sw4) */
#define EN_PROVISIONING_TOGGLE 1
#define EN_ENVIRONMENTAL_SENSOR 0
#define EN_DEBUG_NETWORK_INFO 0

#define SWITCH_ENABLE_BINDING 1
#define EN_EVT_ON_OFF_CONTROL_EXECUTION 1
#define EN_CHECK_SOURCE_CONTROL 1

#define LIGHT_TYPE_HSL_EN 1
#define LIGHT_TYPE_CT_EN 1
#define MD_LIGHTNESS_EN 1

#endif /* APP_DEVICE_H__ */
